// Copyright 1998-2014 Epic Games, Inc. All Rights Reserved.
/*===========================================================================
	C++ class header boilerplate exported from UnrealHeaderTool.
	This is automatically generated by the tools.
	DO NOT modify this manually! Edit the corresponding .h files instead!
===========================================================================*/

#include "ObjectBase.h"

#ifdef FERO_QuadTreeMesh_generated_h
#error "QuadTreeMesh.generated.h already included, missing '#pragma once' in QuadTreeMesh.h"
#endif
#define FERO_QuadTreeMesh_generated_h

#define UQuadTreeMesh_EVENTPARMS
#define UQuadTreeMesh_RPC_WRAPPERS
#define UQuadTreeMesh_CALLBACK_WRAPPERS
#define UQuadTreeMesh_INCLASS \
	private: \
	static void StaticRegisterNativesUQuadTreeMesh(); \
	friend FERO_API class UClass* Z_Construct_UClass_UQuadTreeMesh(); \
	public: \
	DECLARE_CLASS(UQuadTreeMesh, UMeshComponent, COMPILED_IN_FLAGS(0), 0, Fero, NO_API) \
	/** Standard constructor, called after all reflected properties have been initialized */    NO_API UQuadTreeMesh(const class FPostConstructInitializeProperties& PCIP); \
	DECLARE_SERIALIZER(UQuadTreeMesh) \
	/** Indicates whether the class is compiled into the engine */    enum {IsIntrinsic=COMPILED_IN_INTRINSIC};


#undef UCLASS_CURRENT_FILE_NAME
#define UCLASS_CURRENT_FILE_NAME UQuadTreeMesh


#undef UCLASS
#undef UINTERFACE
#define UCLASS(...) \
UQuadTreeMesh_EVENTPARMS


#undef GENERATED_UCLASS_BODY
#undef GENERATED_IINTERFACE_BODY
#define GENERATED_UCLASS_BODY() \
public: \
	UQuadTreeMesh_RPC_WRAPPERS \
	UQuadTreeMesh_CALLBACK_WRAPPERS \
	UQuadTreeMesh_INCLASS \
public: